#!/bin/bash

lang=${1:-$lang}
ctx=${2:-${ctx:-"."}}

g() {
  if [[ $lang == c ]]; then
    echo "gcc"
  elif [[ $lang == cpp ]]; then
    echo "g++"
  else
    echo "false"
    return 1
  fi
}

'$'() {
  file="${1:-main}"
  $(g) -o .main "$file.$lang"
  if [[ -f .main ]]; then
    if [[ -s in ]]; then
      ./.main < in > out
    else
      ./.main
    fi
  fi
  touch .main
  rm .main
}

,() {
  if [[ -z $1 ]]; then
    file=template
  else
    file="$ctx/$1"
  fi
  echo -n > in
  echo -n > out
  cp "$file.$lang" "main.$lang"
}

@() {
  mkdir -p "$ctx/code"
  mkdir -p "$ctx/task"
  cp -n template.yaml "$ctx/progress.yaml"
  if [[ -z $1 ]]; then
    return 1;
  fi
  cp -n "main.$lang" "$ctx/code/$1.$lang"
}

+() {
  if [[ -z $1 ]]; then
    file="temp"
  else
    file="${1}_"
  fi
  while [[ -f "$ctx/$file.$lang" ]]; do
    file="${file}_"
  done
  cp "main.$lang" "$ctx/$file.$lang"
}

-() {
  rm "$ctx/${1:-temp}.$lang"
}

g > /dev/null || return 1
